spring.application.name=inventory-system

spring.datasource.url=jdbc:mysql://mysql-29a214c1-kagamealain2050-0dfb.c.aivencloud.com:27468/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=YOUR_PASSWORD_HERE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
